pull_request_rules:
  - name: merge reviewed PRs from the repo owner
    conditions:
      - author=dbartholomae
      - base=main
      - status-success=build
    actions:
      merge:
        method: merge

  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=build
    actions:
      merge:
        method: merge
