name: build
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.11.5
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'pnpm'
      - name: Install Packages
        run: pnpm install
      - name: Test
        run: npm test
      - uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-results
          path: reports/junit.xml
      - name: Build page
        run: npm run build
        env:
          REACT_APP_ABLY_API_KEY: fake-secret
