name: build
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.11.5
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'pnpm'
      - name: Install Packages
        run: pnpm install
      - name: Test
        run: npm test
      - name: Build page
        run: npm run build
        env:
          REACT_APP_ABLY_API_KEY: fake-secret
