name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install Packages
        run: npm install
      - name: Test
        run: npm test
      - name: Build page
        run: npm run build
        env:
          REACT_APP_ABLY_API_KEY: ${{ secrets.REACT_APP_ABLY_API_KEY }}
          REACT_APP_PUBLIC_URL: ${{ secrets.REACT_APP_PUBLIC_URL }}
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
