name: 'Test Report'
on:
  workflow_run:
    workflows: ['build']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: Jest Tests
          path: '*.xml'
          reporter: jest-junit
